-define(CONSOLE_COLOR_RED,      "\e[0;31m").
-define(CONSOLE_COLOR_RED_BOLD, "\e[1;31m").
-define(CONSOLE_COLOR_GREEN,    "\e[0;32m").
-define(CONSOLE_COLOR_YELLOW,   "\e[0;33m").
-define(CONSOLE_COLOR_BLUE,     "\e[0;34m").
-define(CONSOLE_COLOR_PURPLE,   "\e[0;35m").
-define(CONSOLE_COLOR_CYAN,    "\e[0;36m").
-define(CONSOLE_COLOR_GRAY,     "\e[0;31;37m").
-define(CONSOLE_COLOR_NORMAL,   "\e[0;38m").

-define(MAX_CH,   70).
